#!/bin/bash
.PHONY: astar_pathfinding snake

## General scripts
venv:
	( \
		python3.10 -m pip install --upgrade pip; \
		pip install virtualenv; \
		python3.10 -m venv venv; \
		source venv/bin/activate; \
		pip install -r requirements.txt; \
	)
test: venv
	( \
		source venv/bin/activate; \
		python3.10 -m unittest; \
	)

## A* script
astar_pathfinding: venv test
	( \
		source venv/bin/activate; \
		python3.10 astar_pathfinding/Astar_pathfinding.py; \
	)

## Snake game
snake: venv test
	( \
		source venv/bin/activate; \
		python3.10 main.py snake; \
	)